# Generated by Django 4.1.4 on 2023-05-13 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_deliveryorder_deliveryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryorder',
            old_name='customerID',
            new_name='customer',
        ),
        migrations.CreateModel(
            name='CollectionOrder',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
