# Generated by Django 4.1.4 on 2023-05-13 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_customerid_deliveryorder_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionorder',
            name='pickupTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
